- name: copy composer from /tmp to bin location
  become: true
  tags:
    - php
    - composer
  copy:
    remote_src: true
    src: /tmp/composer.phar
    dest: /usr/local/bin/composer

- name: delete temp composer file
  become: true
  tags:
    - php
    - composer
  file:
    path: /tmp/composer.phar
    state: absent